// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use <code>chrome.performance</code> to retrieve performance data of the
// current extension/app.
// Purely implemented in JavaScript.
namespace performance {
  callback GetRequestsExecutionTimeCallback = void (any performanceData);
  interface Functions {
    static void getRequestsExecutionTime(GetRequestsExecutionTimeCallback
                                         callback);
  };
};